# Generated by Django 5.2.6 on 2025-11-24 15:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('line_id', models.CharField(blank=True, max_length=50, null=True)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('role', models.CharField(choices=[('user', 'สมาชิก'), ('adoptive_parents', 'พ่อแม่บุญธรรม'), ('org_admin', 'แอดมินองค์กร')], default='user', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lost', models.BooleanField(default=False, verbose_name='สุนัขหาย')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อสุนัข')),
                ('gender', models.CharField(choices=[('M', 'Male (ตัวผู้)'), ('F', 'Female (ตัวเมีย)')], max_length=1, null=True, verbose_name='เพศ')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='อายุ')),
                ('personality', models.TextField(blank=True, null=True, verbose_name='นิสัยของสุนัข')),
                ('favorite_food', models.TextField(blank=True, null=True, verbose_name='อาหารโปรด')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='อาหารที่แพ้')),
                ('primary_color', models.CharField(max_length=50, null=True, verbose_name='สีหลัก')),
                ('secondary_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='สีรอง')),
                ('organization', models.BooleanField(default=False, null=True, verbose_name='อยู่ในการดูแลของโฮงเกลือหมาหรือไม่')),
                ('vaccination_history', models.CharField(blank=True, default='', help_text='กรอกชื่อวัคซีนที่ฉีดแล้ว โดยคั่นด้วยเครื่องหมายคอมมา (เช่น DHPPL, Rabies)', max_length=255, verbose_name='รายการวัคซีนที่ฉีดแล้ว')),
                ('sterilization_status', models.CharField(choices=[('NO', 'ยังไม่ทำ/ไม่ได้คุมกำเนิด'), ('SURGICAL', 'ทำหมันถาวร (ผ่าตัด)'), ('CHEMICAL', 'คุมกำเนิดชั่วคราว (เช่น ฉีดยาคุม)')], default='NO', help_text='ระบุว่าสุนัขได้ทำหมันหรือคุมกำเนิดแบบใด', max_length=10, verbose_name='สถานะการควบคุมกำเนิด')),
                ('sterilization_date', models.DateField(blank=True, help_text='ระบุวันที่ดำเนินการล่าสุด', null=True, verbose_name='วันที่ทำหมัน/คุมกำเนิดล่าสุด')),
                ('size', models.CharField(choices=[('ES', 'Extra Small (เล็กมาก)'), ('S', 'Small (เล็ก)'), ('M', 'Medium (กลาง)'), ('L', 'Large (ใหญ่)'), ('XL', 'Extra Large (ใหญ่มาก)'), ('XXL', 'XX Extra Large (ใหญ่พิเศษ)')], max_length=3, null=True, verbose_name='ขนาด')),
                ('distinguishing_marks', models.TextField(blank=True, verbose_name='ลักษณะ/รอยตำหนิเด่น')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dog_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('embedding_binary', models.BinaryField(blank=True, null=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.dog')),
            ],
        ),
        migrations.CreateModel(
            name='FoundDogReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_lat', models.FloatField()),
                ('location_lng', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoundDogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='found_dogs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.founddogreport')),
            ],
        ),
        migrations.CreateModel(
            name='LostDogReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_lat', models.FloatField()),
                ('location_lng', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_found', models.BooleanField(default=False)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dog')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อข่าวสาร')),
                ('content', models.TextField(verbose_name='รายละเอียดเนื้อหา')),
                ('notification_type', models.CharField(choices=[('ACTIVITY', 'กิจกรรมองค์กร/ทั่วไป'), ('DOG_SPECIFIC', 'ประกาศเฉพาะสุนัข'), ('LOST_DOG', 'สุนัขสูญหาย')], default='ACTIVITY', max_length=20, verbose_name='ประเภทข่าวสาร')),
                ('is_important', models.BooleanField(default=False, verbose_name='สำคัญมาก')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications/', verbose_name='รูปภาพประกอบ')),
                ('dog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='myapp.dog', verbose_name='สุนัขที่เกี่ยวข้อง')),
                ('organization', models.ForeignKey(blank=True, limit_choices_to={'role': 'org_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='องค์กรผู้ประกาศ')),
            ],
            options={
                'verbose_name': 'ข่าวสาร/การแจ้งเตือน',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdoptionParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateField(auto_now_add=True, verbose_name='วันที่รับดูแล')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopted_dogs', to=settings.AUTH_USER_MODEL, verbose_name='พ่อแม่บุญธรรม')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_parents', to='myapp.dog', verbose_name='สุนัข')),
            ],
            options={
                'verbose_name': 'พ่อแม่บุญธรรม',
                'unique_together': {('user', 'dog')},
            },
        ),
    ]
