# Generated by Django 5.2.6 on 2025-12-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='lost_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='ละติจูด (Latitude)'),
        ),
        migrations.AddField(
            model_name='dog',
            name='lost_location_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='รายละเอียดสถานที่สูญหาย'),
        ),
        migrations.AddField(
            model_name='dog',
            name='lost_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='ลองจิจูด (Longitude)'),
        ),
    ]
