# Generated by Django 5.2.6 on 2026-01-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dog_lost_latitude_dog_lost_location_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.CharField(default='00:00', help_text='Format: HH:MM (24h)', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Training Configuration',
                'verbose_name_plural': 'Training Configurations',
            },
        ),
    ]
