# Generated by Django 5.2.6 on 2026-01-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_trainingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingconfig',
            name='frequency',
            field=models.CharField(choices=[('daily', 'รายวัน'), ('weekly', 'รายสัปดาห์'), ('monthly', 'รายเดือน')], default='daily', max_length=10),
        ),
    ]
