# Generated by Django 5.2.6 on 2026-01-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_trainingconfig_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='KNNTrainingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tsne_image', models.ImageField(upload_to='knn/tsne/')),
                ('knn_matrix_image', models.ImageField(upload_to='knn/matrix/')),
                ('count', models.IntegerField()),
                ('accuracy', models.FloatField()),
            ],
        ),
    ]
