# Generated by Django 5.2.6 on 2026-01-28 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_trainingconfig_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'รอการตรวจสอบ'), ('APPROVED', 'อนุมัติ'), ('REJECTED', 'ปฏิเสธ')], default='PENDING', max_length=20, verbose_name='สถานะคำขอ')),
                ('request_reason', models.TextField(blank=True, null=True, verbose_name='เหตุผลความต้องการ')),
                ('admin_feedback', models.TextField(blank=True, null=True, verbose_name='เหตุผลจากแอดมิน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ส่งคำขอ')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to='myapp.dog', verbose_name='สุนัข')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ขออุปการะ')),
            ],
            options={
                'verbose_name': 'คำขอเป็นพ่อแม่บุญธรรม',
                'ordering': ['-created_at'],
            },
        ),
    ]
