# Generated by Django 5.2.6 on 2026-01-28 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_adoptionrequest'),
        ('myapp', '0005_knntrainingresult'),
    ]

    operations = [
    ]
