# Generated by Django 5.2.6 on 2026-01-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_merge_0005_adoptionrequest_0005_knntrainingresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='knntrainingresult',
            name='model_name',
            field=models.CharField(default='unknown', max_length=255, verbose_name='ชื่อ Model ที่ใช้'),
        ),
    ]
