# Generated by Django 5.2.6 on 2026-02-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_knntrainingresult_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'สมาชิก'), ('org_admin', 'แอดมินองค์กร')], default='user', max_length=20),
        ),
    ]
