"""
Django settings for findmydog project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file at project root (same level as manage.py)
load_dotenv(BASE_DIR / ".env")
FASTAPI_BASE_URL = os.getenv("FASTAPI_BASE_URL")
AUTO_TRAIN_SECRET = os.getenv("AUTO_TRAIN_SECRET")
GOOGLE_MAPS_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^eo&+zc8@%r*!22s)j7ttz18#=j*o(r7d()^g4-aor6l7cwk3d'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.app",
]

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "web",  # Docker service name
    ".ngrok-free.app",   # อนุญาตทุกซับโดเมนของ ngrok
]

# Google Maps API key (loaded from .env)
GOOGLE_MAPS_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY", "")

# Application definition

TRAIN_KNN_HOUR = 2      # เทรนตอนตี 2
TRAIN_KNN_MINUTE = 0 

LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    'myapp.apps.MyappConfig',  # ใช้ AppConfig เพื่อให้ signals ทำงาน
    'tailwind',
    'theme',
    # 'django_browser_reload',
    "django_crontab",
    'django_apscheduler',
    'django_celery_beat'
]


# CRONJOBS = [
#     (
#         '*/1 * * * *',
#         # '0 2 * * *',  # ตี 2 ทุกวัน (แนะนำกว่ารันทุกนาที)
#         'myapp.serverFast.trainKNN',
#         '>> /Users/macbookair/Documents/projects_dog/django/FindMyDog/findmydog/cron_debug.log 2>&1'
#     ),
# ]

CRONJOBS = [
   (
       '*/1 * * * *',
       'myapp.serverFast.trainKNN', 
       '>> /tmp/cron_debug.log 2>&1'
   ),
]
# CRONJOBS = [
#    (
#        '*/1 * * * *',
#        'print',
#        '["Hello from Cron"]', # ส่ง argument ให้ print
#        '>> /tmp/cron_test.log'
#    ),
# ]
# แล้วใช้ตัวนี้คุม Log แทน (เพิ่มไว้ใน settings.py)
CRONTAB_COMMAND_SUFFIX = '>> /tmp/cron_debug.log 2>&1'
CRONTAB_DJANGO_PROJECT_PATH = '/app'
CRONTAB_PYTHON_EXECUTABLE = '/usr/local/bin/python'

AUTO_TRAIN_SECRET = os.getenv("AUTO_TRAIN_SECRET")

# CRONJOBS = [
#     ('*/1 * * * *', 'myapp.cron.my_scheduled_job', '>> /Users/macbookair/Documents/api-project/FindMyDog/cron_debug.log 2>&1')
# ]

MEDIA_ROOT = os.path.join(BASE_DIR,'dog_images')
MEDIA_URL = '/dog_images/'

AUTH_USER_MODEL = "myapp.User"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # เพิ่ม WhiteNoise สำหรับ serve static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
    
ROOT_URLCONF = 'findmydog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'myapp' / 'templates' / 'myapp'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'myapp.context_processors.google_maps_api_key',
            ],
        },
    },
]

WSGI_APPLICATION = 'findmydog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'mydb',            # ชื่อ Database ที่สร้างไว้ใน PostgreSQL
#         'USER': 'admin',           # ชื่อ User ของ Database
#         'PASSWORD': '1234',        # รหัสผ่านของ User
#         'HOST': 'localhost',       # ถ้าอยู่ในเครื่องเดียวกันใช้ localhost หรือ 127.0.0.1
#         'PORT': '5432',            # Port มาตรฐานของ PostgreSQL คือ 5432
#     }
# } 
# DATABASES = {
#     'default': dj_database_url.parse(
#         # "postgresql://postgres:wJTBwSaKjmwVPbiWJAwxhiVWXDGXrIxB@interchange.proxy.rlwy.net:19586/railway"
#         "postgresql://postgres:boss123454@db.pckuwfauavyojghhmdzz.su  pabase.co:5432/postgres"
#     )
# }

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.getenv("POSTGRES_DB", "mydb"),
#         "USER": os.getenv("POSTGRES_USER", "admin"),
#         "PASSWORD": os.getenv("POSTGRES_PASSWORD", "1234"),
#         "HOST": os.getenv("DB_HOST", "localhost"),
#         "PORT": os.getenv("DB_PORT", "5432"),
#     }
# }
import os
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "djdb"),
        "USER": os.getenv("DB_USER", "user"),
        "PASSWORD": os.getenv("DB_PASSWORD", "pass"),
        "HOST": os.getenv("DB_HOST", "db"),     # สำคัญ
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CRONTAB_COMMAND_PREFIX = (
    "DB_NAME=findmydog "
    "DB_USER=admin "
    "DB_PASSWORD=changeme "
    "DB_HOST=db "
    "DB_PORT=5432 "
    "CELERY_BROKER_URL=redis://redis:6379/0 "
    "PATH=/usr/local/bin:/usr/bin:/bin"
)

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    # ลบ BASE_DIR / "static" ออกเพราะไม่มี directory นี้
    # static files อยู่ใน myapp/static/ แล้ว
]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration สำหรับ serve static files ใน production
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
